{
 "title": "Training Data",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "ActivityGPS",
    "label": "Activity with GPS",
    "query": {
     "query": "SHOW TAG VALUES FROM \"ActivityGPS\" WITH KEY = \"ActivitySelector\" WHERE $timeFilter"
    }
   },
   {
    "name": "TimeZone",
    "label": "Local Time Zone",
    "query": "Europe/Budapest, America/Toronto, Asia/Kolkata, America/Sao_Paulo"
   }
  ]
 },
 "panels": [
  { "title": "Training Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Sync ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "HeartRateIntraday",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Body Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "alias": "Body Battery",
     "measurement": "BodyBatteryIntraday",
     "select": [
      [
       { "params": [ "BodyBatteryLevel" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Rest",
     "measurement": "StressIntraday",
     "select": [
      [
       { "params": [ "stressLevel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stressLevel::field", "operator": "<=", "value": "25" }
     ]
    },
    {
     "alias": "Stress",
     "measurement": "StressIntraday",
     "select": [
      [
       { "params": [ "stressLevel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stressLevel::field", "operator": ">", "value": "25" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Training Readiness",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TrainingReadiness",
     "select": [
      [
       { "params": [ "score" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Body Battery",
     "measurement": "BodyBatteryIntraday",
     "select": [
      [
       { "params": [ "BodyBatteryLevel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Training Readiness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 9 },
   "targets": [
    {
     "alias": "Score",
     "measurement": "TrainingReadiness",
     "select": [
      [
       { "params": [ "score" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep Stages",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "alias": "Light",
     "measurement": "SleepIntraday",
     "select": [
      [
       { "params": [ "SleepStageLevel" ], "type": "field" },
       { "params": [ " +1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "SleepStageLevel::field", "operator": "Is", "value": "1" }
     ]
    },
    {
     "alias": "Deep",
     "measurement": "SleepIntraday",
     "select": [
      [
       { "params": [ "SleepStageLevel" ], "type": "field" },
       { "params": [ "+1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "SleepStageLevel::field", "operator": "Is", "value": "0" }
     ]
    },
    {
     "alias": "REM",
     "measurement": "SleepIntraday",
     "select": [
      [
       { "params": [ "SleepStageLevel" ], "type": "field" },
       { "params": [ "+1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "SleepStageLevel::field", "operator": "Is", "value": "2" }
     ]
    },
    {
     "alias": "Awake",
     "measurement": "SleepIntraday",
     "select": [
      [
       { "params": [ "SleepStageLevel" ], "type": "field" },
       { "params": [ "+1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "SleepStageLevel::field", "operator": "Is", "value": "3" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Recovery Time",
     "measurement": "TrainingReadiness",
     "select": [
      [
       { "params": [ "recoveryTime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Sleep Score",
     "measurement": "TrainingReadiness",
     "select": [
      [
       { "params": [ "sleepScore" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Race Predictions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "5KM",
     "measurement": "RacePredictions",
     "select": [
      [
       { "params": [ "time5K" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "10KM",
     "measurement": "RacePredictions",
     "select": [
      [
       { "params": [ "time10K" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Half Marathon",
     "measurement": "RacePredictions",
     "select": [
      [
       { "params": [ "timeHalfMarathon" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Marathon",
     "measurement": "RacePredictions",
     "select": [
      [
       { "params": [ "timeMarathon" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Training Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 17 },
   "targets": [
    {
     "alias": "Min Training Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TrainingStatus",
     "select": [
      [
       { "params": [ "minTrainingLoadChronic" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Max Training Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TrainingStatus",
     "select": [
      [
       { "params": [ "maxTrainingLoadChronic" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Training Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TrainingStatus",
     "select": [
      [
       { "params": [ "dailyTrainingLoadAcute" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "HRV Status (Vo2Max)",
     "measurement": "TrainingReadiness",
     "select": [
      [
       { "params": [ "hrvWeeklyAverage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Endurance Score",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 24 },
   "targets": [
    {
     "alias": "Endurance Score",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EnduranceScore",
     "select": [
      [
       { "params": [ "EnduranceScore" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hill Score",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 24 },
   "targets": [
    {
     "alias": "Hill Score",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HillScore",
     "select": [
      [
       { "params": [ "overallScore" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Hill Endurance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HillScore",
     "select": [
      [
       { "params": [ "enduranceScore" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Hill Strength ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HillScore",
     "select": [
      [
       { "params": [ "strengthScore" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart Rate Distribution",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Heart rate histogram",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value <= 96",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Heart rate histogram > 96",
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value > 96",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Heart rate histogram < 60",
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value < 60",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Heart rate histogram > 110",
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value > 110",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}