version: "3"

services:
  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./config:/app
      - /mnt/friday-pool/all/downloads/incomplete:/incomplete
      - /mnt/friday-pool/all/media/music:/music
    ports:
      - 5030:5030
      - 5031:5031
    networks:
      - music-stack

networks:
  music-stack:
    external: true
